// <auto-generated />
namespace MupadoodleAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class markets : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207251653535_markets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy/WKwJazcr8+OXZWNp/lB6XRUa4vM7L8/dEbOchEPvIdkmdnhJy7fWb61XOHaPPJl8vPkqfZE2Oj6Wj8fNqmrVED/9lev1lXa3yur0OXj57+lEqr54t23t7H6Uv1mWZTUr64Dwrm/yj9O5GKFPC6HVbGyD0K83QR+mz4l0+e54vL9q5BfRF9s58sr+zQxP11bKgGaW32nqd+z3L35s7bubZKv/hd9vm5Q+/03X9c9BpNqvzptn9ueiYe9774ff8g2L1s93p47tOijfK9gn9eVvJfpFdFhf8RZdb66xYvm75K9JGr/JSfp0XK4WIbn7/TrNndbV4VZWKRPjt7/+6WtdTCF412ORNVl/kbY/Yg1iSJqyqcgN+tkEHM/08jpP58n2xmVfNqmizTfh4TToY2W/iOLmv3xery3y5zjegZL7v4CMfx5HR794XkwXbjQ2o2AYdXPTzODLmy/fFZpXVbzfgol93MOFP43jIV++LxYLeyttNNDENujSRzwdool/GsLm1HnnjieawPglh94C8Zln62q9/W9n+awMY0Hu/V34dfOBp9Ff5eeddeDqd+bzbBdA1CP67m72k1aePXrdVnX+eL/M6a/PZy6xt85p80rNZzsNR/+/R6tPbuYAP7+7swQW8my2XlZm/zfarrJYX"
                       + "RbueWb/oabUmJN/bqQMPfxNglvTj/zUG9QuWptua1K6zzC/fzAY/cpb9bn8Y8x+TAqNUfnZ7vjXnvSTm+Zp8h1d/xHXv1202reEJfZDqWpUZm+OfVdSHGOi4aappwdzhBQMdLz1E/3Q5S2922R33SXTxxbpsi1VZgEM++2hnPN7t0WUjYOOYeIBDdyPs4Fvd4XsDvcX4TRSwEcFeSPDhY+4GEh5I4xd9o+N00cVGtCKhxoePtR+geECdG/eNjldDl414deOYDx9pJ/qJOqXf6DBNWLQRq16M9OED7UZWHkiTP/xGxykh10aUOvHXh48xjNo8gGJ6v9HxmVBuM9G7cd2Hj7EbDfrzqK7t1xunGCHKdbekuvNax3o8nVIS7umT3jjR+HXediIkMrjOmG2M7kLKOkg8SNgXLxPlNfSj6Q2WsE+3uC204wiGEOJ5EywzE7eBFVCfmt6WIDb1NUCKqFHsI941i7dBeRjKD2PgXo5tYOgDdrKPdt9S3gbxTXB+GARQszg0+pjV7KPcsZu3wXcQyA9j0DZ3ODDqqBGN6MqOGb0NysNQfhgD10TlwLAjNnXICH7YkENDehsYX3fANiM6NNMxM3uzob0Nyjfb1ttA2TBwE9hZm2q/e3xXVo71g8d3B5aYH3+RrVYUdHpLzvpJ+lrWm0+2X7//ivJCYNydBnTtegC2J0poZhd551vqmjB9VtRN+zRrs0mGMPhktug1u8mDMN10HYmj3lwZv8K8gd81LxdZdTdubWfOHQmf0agWlJTlAerwgrnuv5piyT8rs3pDgvikKteLZf/zLvMNQ3NL8j4s9+ntIcED5JyPD8h+eHs4msLxoehHt4fRYsnch8Af3P59Xv323+cPbv++Xcj2YdgP3weOWZcOAZlPbw+J15l9IPxB9H2Sp1kBTkp/MivXlhvC158WzbQuFsUyI4aOAXp8t8P6XX3oZaK0ZV9jvqcUQrH+v1sGe7RllP/fT9kgx/b/LQqH6cH/"
                       + "11Na83v/36KxSUr+v566Np/4/y36ujTo/5sofNbg9y/Pt76IkdqM8s7/u2kdheatavvAvI/fAxb1HwFlP30PSMsMi5sBGPnohz71X0SdYMkJ/n9vut1Se+AE209vD2mTE/xent+QF/xeQPr8MsQuw4KgM9ORA/Pp7dSXSRb/v0l5fRHjYM7d/3+Pf82SvQ/JfHZ7KJt4971ijSHefS8guqQexD3y0e1h6JK6D0M/CmEojB7fylLO/+u5dpj9/t/EuT3q2r5/uBQ237t0UPh1mGIzUyDIceaus2B0i5i0+8ptZwE5ww75++BMHrJPqPeaPwa8aRJBN4vN10L0jaQ6PxDRr42jY8Cz5sW6LD/76JwWVjr64QYydDOwX4+D7ArbbXjHNv5QruksyH3gNHQIFfFLvg7DdJb7PhDHHyqr9FfTvxFe8RYlb8MtXvMP5ZfeGuYHzkaHXhFv4OtwTG+F9AOx/KHyTI8G3wzPmHXc2zCMafuh3BIu+37gJHTIdO89p2Iziv8f5JMeAb4ZPrFL37dhFNv4Qzmls1L+gfPQodT+e87GDTj+f5BXehT4ZniFl+lvxyna9EP5hMH87HDJ/fech40Y/n+QR3rj/2Z4ZMF5nltyiW38oXyigD6IUwYp9el7zsYNOP5/kFd6FLiZV0yITd21FADmdbeJjeH1E/t3Yz4AU2QXuTCMe48WmvJFxuRpVpTJIWypxbOibtqnWZtNsiaXJh+lRIPLYpbXtDp13bT5YowG49e/qHyd15d5fZKP98c7rtkX2bI4z5v2TfU2X372EX93XBZZQ+/n5flH6btFuaQ/5m27enT3bsO9NONFMa2rpjpvx9NqcZdY/e7ezs7Duzt7d/PZ4m7TzIKlJi+305nikCUe/155b+7MnL7KzyPs0Z2iLgD7euRdoPPZR8WyVVn8PKcpy9p89jJr27wmapzNckb8oxRck03K3HJOp+NON96KifRyXlZZ+/5gMrNa8kFQlhmy3wJi"
                       + "eZnV03lGKaYvsnfP8+VFO6dZ39nZ8cG29fpGqF+wq9Ch4/uBmEL1IfP6DaOmidhvGGqbl984zHX9zcPMZpQubnZ/FuAy4L1vHPAPitU3DtMtYn0od37zhDQLWt8w2PeW8tsALY2e/qaxNes0Hzo93zw7mjWbbxisruIMKPLbQNA1nG8Yr87Cwwbou3sH7217Ok7VB8x3B5KVnw8HZef6w0Hd++ZA7X9zoO5/c6A+vTUofz3K/9hzov0uwqWiECXy7NNXFbqxbqNiARfVrQOmX6zLtliVBXTDZx/tjMf95HQflri5t4D3rR4w8knzGi5iVpLP3/AYeutyL+tiOS1WWdkdQ6ehR/vb+LqgsAXd/eZpvsqXcF5jY71Nvz257Xdu+whpcvcmogRx1C04wywE/Ygn/t/FE9GlL9vJzzJTuPWeH7HF/7vYIrq+ZTv5WWYLXdX5EU/8v4snogtZtpOfZZ4wCzg/Yor/dzHF/s8lU8hazY9Y4v9dLHH/55IlzMLMj5ji/11M0VuI+VlhCglW7cqNQaW7ytLjDl2+65Dso9QFv72ZlZWazz6aTSqae4mfzbdNb57DRafhkDn1GmqXNwXWA+xtB+V/2JuCIWa+xdvdlbTbDthEgkNDjUaK/18bpItshoY5EPv8f22g6qsPjTLmyv9/bYjG9RwaY9Q1/WEO8psYpLhSQ0OMOFr/XxugcQwGZzHmOPy/cJAmI2uNnP3u8V2xSfoB/UlrAdlF/gWZv7LhT8m0runtheRyycg3xYUD8ZhgLvMp+nRATZuz5XllrHwHI9Okk3T+Im+zGVnc47otzrNpS19PaemxWF58lP5kVq6pyeliks/Oll+u29W6pSHni0l57RMDPsKm/h/f7eH8+MsV/mq+iSEQmgUNIf9y+WRdlDOL97P+qskQCDgfn+f0ucwlGfI2v7i2kF5Uy1sCUvI9NT7Tm3xBa0lt3ny5fJ1d5sO43UzDkGKPnxbZRZ0tGoXh3qc/if1m"
                       + "i3dH/08AAAD//yL+C8BzZAAA"; }
        }
    }
}
