// <auto-generated />
namespace Mupadoodle1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207092043314_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy/WKwJazcp8dyytP0qPyyIjTF7n5fl7orXzEGh9ZDukLk8Jtfb6zfUq527RY5OvgzbU6vfKr4MP6KOXdbXK6/b6VX6ubxazj9K74Xt3uy/a17x30PlnH50t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27ymaTmb5Yy8EuHR6tPb0eHh3Z090OFutlxWbdbSHIeIP77rqNKnFU1fmxWEjA7heDrNm+bpkw7JpPHrvNVmC6YrTZ+DLXM4VopHUbCdOSa5K1xiuOnuADs9/iJbrYivPfbST9LXwlsn26/fn38WAuPutImwkcXW9kQzl13knW+pa8L0WVE37dOszSYZ5vlktug1u4m0ppuQwl1OdQQ37fG74faufJnp6EBx5HtGI1oQ5/HgdGiES1xy9NXX06zM6gjvn1TlerEckh9+926n3+7wPGbVlh0Z7JJrE5t1m9jeLbt12OqxTvHNqqw359Lko5TIclnMMN+vr5s2X4zRYPz6F5Wv85p09Uk+3ocCNs2+yJbFed60b6q3OWkB/u7rqkSrCppmVv6/Uy8Wy/aj9EYN2FObX1+f9WVzs2Iz6mtQr8k8f/bRbFLRoATLL4w2/JpKr891j+/6Zvbx07wpLhwIGN1lPoWud0BNm7PleWXo"
                       + "T+PyMTJNOtPzRd5mMyLPcd0W59m0pa+hqUguPkp/MivX1OR0MclnZ8sv1+1q3R43Tb6YlNf+eB/f3dw/a/YQ58dfrvCXJ2ZffwiEZkFDyL9cPlkX5czi/SzCPwMgwCnKlITV6xbMeXFtIb2olrcEpOR7mq/yJVj6Tb5YlQSs+XL5OrvMh3G7mYYhxR4/LbKLOls0CsO9T38S+5HPdvT/BAAA//+E5+MpKAoAAA=="; }
        }
    }
}
