// <auto-generated />
namespace Mupadoodle1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class creating_museum_table : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207071602276_creating_museum_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy/WKwJazcp8dyytP0qPyyIjTF7n5fl7orXzEGh9ZDukLk8Jtfb6zfUq527RY5OvgzbU6vfKr4MP6KOXdbXK6/b6VX6ubxazj9K74Xt3uy/a17x30PlnH50t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27ymaTmb5Yy8EuHR6tPb0eHh3Z090OFutlxWbdbSHIeIP77rqNKnFU1fmxWEjA7heDrNm+bpkw7JpPHrvNVmC6YrTZ+DLXM4VopHUbCdOSa5K1xiuOnuADs9/iJbrYivPfbST9LXwlsn26/fn38WAuPutImwkcXW9kQzl13knW+pa8L0WVE37dOszSYZ5vlktug1u4m0ppuQwl1OdQQ37fG74faufJnp6EBx5HtGI1oQ5/HgdGiES1xy9NXX06zM6gjvn1TlerEckh9+926n3+7wPGbVlh0Z7JJrE5t1m9jeLbt12OqxTvHNqqw359Lko5TIclnMMN+vr5s2X4zRYPz6F5UnZUHjdQ2+yJbFed60b6q3OdQyseTX14ZWCzTNrPx/p0osMPgblV9PY359VdYXy806zWiuQZUmU/zZR7NJRYMSLL8wivBr6rs+wz2+61vYx0/zprhwIGBvl/kUat4BNW3OlueVoT+Ny8fINOlM"
                       + "zxd5m82IPMd1W5xn05a+hpIikfgo/cmsXFOT08Ukn50tv1y3q3V73DT5YlJe++N9fHdz/6zUQ5wff7nCX56Eff0hEJoFDSH/cvlkXZQzi/ezCP8MgACnKFMSVq9bMOfFtYX0olreEpCS72m+ypdg6Tf5YlUSsObL5evsMh/G7WYahhR7/LTILups0SgM9z79SexH7trR/xMAAP//ZgzVIiMKAAA="; }
        }
    }
}
