// <auto-generated />
namespace DemoApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206262221599_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so6f5ojpercpimrWEy1je+Cg9LouMsHmdl+fvidrOQ6D2ke2Uuj0l9NrrN9ernLv+7KPTd9N5trzIX2Vt7rektr9Xfh18QB+9rKtVXrfXr/Jzfb+YfZTeDd+7233Rvua9AxQ+++hs2d7b+yh9sS7LbFLSB+dZ2eQfpatPH71uqzr/PF/mNWE2e5m1bV7TBJ3Nch6CkuLR6tPbUePh3Z09UONutlxWLVO4h3gHzfO6Wpys65rY5tog/LqtiYE+Sp8V7/LZ83x50c4t0l9k78wn9OtH6VfLgviNXmrrde4PUv7e3Hlb/Zx1DYKbTp9Wa3ovMkM+iMd3HVv1mY1koM0KmscOxz2ddPhNmr/OW22Ye6xJcuD6EGEYB6wbRch27eTurgieEdC7AxL6+ItstSJyexKrn6SvRVxPtl+/vzguBMbdaRORSout7YlEILvIO99S14Tps6Ju2qdZm00yTMfJbNFrdjOhTUcxendF35HfvIXf5c246gonqAPPEfQZjXFBQs3D1cESbptUkwJ4Pc3KrI4ol5OqXC+WQwpq09uhzPtwwm9uD9EXZB+e//ntoYls+nDqHvfr+3c79O1OqCe02rKjxrtssknAuk1s71bQOgL1WJn7ZrvY43Zp8lFKpLksZuD019dNmy/GaDB+/YvK"
                       + "k7Kg8boGX2TL4jxv2jfV2xw2noTx65tVa0iaZlb+v9m2FiDBjVZ0o2Lvg4/ZxOVlVtNA661F9u7O+xqbvp37IHC+7Tovq6z9Rk1XX/FutmChhbrBgAlbf/bRbFLRCARjv0XztW1cX9Qe3/Ud1cdP86a4cCDgti7zKVS5A2ranC3PK0N0GqmPkWnSmZMv8jabEcGO67Y4z6YtfT3Nm4admZ/MyjXGuZjks7Pll+t2tW6PmyZfTMpALz6+u7l/NuQhzo+/XOEvT7d8/SEQmgUNIf9y+WRdlDOL97MIRw2AAO+oIBJW5MwRuItrC+lFtbwlICXf03yVLyHGb/LFqgR/fLl8nV3mw7jdTMOQYo+fFtlFnS0aheHepz+J/SjqOfp/AgAA//97wUPZag0AAA=="; }
        }
    }
}
